/*
https://projecteuler.net/problem=2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

const eFib = require('./002-fibonacci-even.js')

test('The sum of even-valued terms in the Fibonacci sequency of terms whose values do not exceed 6 is equal to 2', () => {
  expect(eFib(6)).toBe(2)
})

test('The sum of even-valued terms in the Fibonacci sequence of terms whose values do not exceed 8 is equal to 10', () => {
  expect(eFib(8)).toBe(10)
})

test('The sum of even-valued terms in the Fibonacci sequence of terms whose values do not exceed 21 is equal to 10', () => {
  expect(eFib(21)).toBe(10)
})

test('The sum of even-valued terms in the Fibonacci sequence of terms whose values do not exceed 21 is equal to 10', () => {
  expect(eFib(55)).toBe(44)
})

test('The sum of even-valued terms in the Fibonacci sequence of terms whose values do not exceed 21 is equal to 10', () => {
  expect(eFib(88)).toBe(44)
})

test('The sum of even-valued terms in the Fibonacci sequence of terms whose values do not exceed 4 million is equal to 4,613,732', () => {
  expect(eFib(4000000)).toBe(4613732)
})
